In [2]:
!pip install torch
!pip install torchvision

In [3]:
import torch
import math
print(torch.__version__)

2.3.1


### Components of a Neural Network That We Have Talked About
- The number of hidden layers
- The number of units in a hidden layer
- Activation functions performed at the various layers
- The loss function that we try to optimize for
- The learning rate associated with the neural network
- The batch size of data leveraged to build the neural network
- The number of epochs of forward and back-propagation

However, for all of these, we built them from scratch using NumPy arrays in Python. In this notebook, we will learn about implementing all of these using PyTorch on a toy dataset.

In [10]:
# Input and output values

x = [[1,2],[3,4],[5,6],[7,8]]
y = [[3],[7],[11],[15]] # Output = Sum of values in inpout list

# Convert into floats
# It is good practice to have tensor objects as floats or long ints, as they will be multiplied by decimal values (weights) anyway.
X = torch.tensor(x).float()
Y = torch.tensor(y).float()

print(X)
print(Y)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[ 3.],
        [ 7.],
        [11.],
        [15.]])


In [12]:
# Register the input (X) and output (Y) data points to the device – cuda if you have a GPU and cpu if you don't have a GPU:

device = 'cuda' if torch.cuda.is_available() else 'cpu'

X = X.to(device)
Y = Y.to(device)

In [17]:
# Define the Neural Network Architecture

import torch.nn as nn

class MyNeuralNet(nn.Module): # inheriting from nn.Module
    def __init__(self):
        super().__init__()  # We should call super().__init__() to ensure that the class inherits nn.Module:

        # Define layers in NN
        self.input_to_hidden_layer = nn.Linear(2,8)
        self.hidden_layer_activation = nn.ReLU()
        self.hidden_to_output_layer = nn.Linear(8,1)

        # For now, the choice of number of layers and activation is arbitrary.
        # We'll learn about the impact of the number of units in layers and layer activations in more detail later

    # Let's connect the components together while defining the forward propagation of the network
    # It is mandatory to use forward as the function name since PyTorch has reserved this function as the method for 
    # performing forward propagation. Using any other name in its place will raise an error.
    def forward(self, x):
        x = self.input_to_hidden_layer(x)
        x = self.hidden_layer_activation(x)
        x = self.hidden_to_output_layer(x)
        return x    

In [21]:
# Accessing weights and bias

testnn = MyNeuralNet().to(device)
print(testnn.input_to_hidden_layer.weight)
print(testnn.input_to_hidden_layer.bias)

Parameter containing:
tensor([[ 0.4101,  0.5737],
        [ 0.3459, -0.0734],
        [ 0.5421,  0.1373],
        [ 0.2868, -0.0571],
        [ 0.1646, -0.6410],
        [ 0.5123,  0.1445],
        [ 0.6824,  0.3221],
        [ 0.5782,  0.7057]], requires_grad=True)
Parameter containing:
tensor([ 0.5125, -0.6074, -0.0498, -0.0398,  0.0804,  0.0949, -0.6229, -0.2854],
       requires_grad=True)


In [23]:
# Or get all params at once

testnn.parameters() # this returns a generator that you can iterate over

for par in testnn.parameters():
    print(par)

Parameter containing:
tensor([[ 0.4101,  0.5737],
        [ 0.3459, -0.0734],
        [ 0.5421,  0.1373],
        [ 0.2868, -0.0571],
        [ 0.1646, -0.6410],
        [ 0.5123,  0.1445],
        [ 0.6824,  0.3221],
        [ 0.5782,  0.7057]], requires_grad=True)
Parameter containing:
tensor([ 0.5125, -0.6074, -0.0498, -0.0398,  0.0804,  0.0949, -0.6229, -0.2854],
       requires_grad=True)
Parameter containing:
tensor([[-0.1254,  0.2876, -0.1096, -0.0509,  0.1335, -0.0922, -0.0472, -0.3466]],
       requires_grad=True)
Parameter containing:
tensor([-0.2388], requires_grad=True)


- The model has registered these tensors as special objects that are necessary for keeping track of forward and backward propagation.
- When defining any nn layers in the __init__ method, it will automatically create corresponding tensors and simultaneously register them.

### Manually Register Parameters
- You can also manually register these parameters using the nn.Parameter(<tensor>) function. Hence, the following code is equivalent to the neural network class that we defined previously.

In [25]:
# This model is equivalent to the previous implementation but uses the underlaying Parameter and torch.rand functions
class MyNeuralNet(nn.Module):
     def __init__(self):
        super().__init__()
        self.input_to_hidden_layer = nn.Parameter(torch.rand(2,8))
        self.hidden_layer_activation = nn.ReLU()
        self.hidden_to_output_layer = nn.Parameter(torch.rand(8,1))
 def forward(self, x):
        x = x @ self.input_to_hidden_layer
        x = self.hidden_layer_activation(x)
        x = x @ self.hidden_to_output_layer
        return x

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 8)